services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
        - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data2
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - 5051:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.container_name
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pg_admin:/var/lib/pgadmin

volumes:
  postgres-data:
  pg_admin:
